import raw from '../generated/catalog.json';
import content from './content.json';

export const RARITIES = ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary'] as const;
export type Rarity = (typeof RARITIES)[number];

export const RARITY_JA: Record<Rarity, string> = {
  Common: 'コモン',
  Uncommon: 'アンコモン',
  Rare: 'レア',
  Epic: 'エピック',
  Legendary: 'レジェンド',
};

export const RARITY_COLOR: Record<Rarity, string> = {
  Common: '#b9b9b9',
  Uncommon: '#63d471',
  Rare: '#4fa8ff',
  Epic: '#c77dff',
  Legendary: '#ffb627',
};

export type Family = keyof typeof content.families;
export const FAMILIES = content.families as Record<Family, { name: string; priceMult: number }>;

export interface Extension {
  id: number;
  name: string;
  rarity: Rarity;
  rarityIndex: number;
  seriesIndex: number;
  seriesName: string;
  family: Family;
  /** The "真" re-release of a Legendary (rarer, pricier, own art). */
  shin: boolean;
  skill: string;
  image: string;
}

export interface Hero {
  id: number;
  name: string;
  rarity: Rarity;
  rarityIndex: number;
  faction?: string;
  passive?: string;
  image: string;
}

export interface Frame {
  image: string;
  ms: number;
}

export const catalog = raw;

/** Sprite sheets generated by scripts/sync-assets.mjs, keyed by sheet name (e.g. "ext-0"). */
export const atlases = raw.atlases as Record<string, { url: string; cols: number; rows: number; cell: number }>;

type RawSeries = (typeof raw.series)[number];

/** Every extension series in the asset database (Legacy and Modern). */
export const allSeries: RawSeries[] = raw.series;

/** The series the game currently uses, in skill-tree order (see content.json). */
export const series = content.activeSeries.map(({ key, family }, seriesIndex) => {
  const s = raw.series.find((x) => x.expansion === 'legacy' && x.key === key) ?? raw.series.find((x) => x.key === key);
  if (!s) throw new Error(`series not in catalog: ${key}`);
  const toExt = (e: (typeof s.items)[number]): Extension => ({
    id: e.id,
    name: e.name,
    rarity: e.rarity as Rarity,
    rarityIndex: RARITIES.indexOf(e.rarity as Rarity),
    seriesIndex,
    seriesName: s.name,
    family: family as Family,
    shin: e.shin,
    skill: e.skill,
    image: e.image,
  });
  // One item per rarity, Common → Legendary (series with variants use the first of each rarity).
  const items = RARITIES.map((r) => {
    const e = s.items.find((i) => i.rarity === r && !i.shin);
    if (!e) throw new Error(`series ${key} has no ${r}`);
    return toExt(e);
  });
  const shinRaw = s.items.find((i) => i.shin);
  return { key: s.key, name: s.name, family: family as Family, items, shin: shinRaw ? toExt(shinRaw) : null };
});

export const extensionById = new Map<number, Extension>(
  series.flatMap((s) => (s.shin ? [...s.items, s.shin] : s.items)).map((e) => [e.id, e]),
);

export function getExtension(id: number): Extension {
  const e = extensionById.get(id);
  if (!e) throw new Error(`unknown extension ${id}`);
  return e;
}

const toHero = (h: (typeof raw.heroes)[number]): Hero => ({
  id: h.id,
  name: h.name,
  rarity: h.rarity as Rarity,
  rarityIndex: RARITIES.indexOf(h.rarity as Rarity),
  faction: h.faction,
  passive: h.passive,
  image: h.image,
});

export const heroById = new Map(raw.heroes.map((h) => [h.id, h]));
const byId = <T>(map: Map<number, T>, id: number, what: string): T => {
  const v = map.get(id);
  if (!v) throw new Error(`${what} ${id} not in catalog`);
  return v;
};

/** Villain heroes that play thieves (see content.json and thieves.ts). */
export const thieves: Hero[] = content.thiefIds.map((id) => toHero(byId(heroById, id, 'thief hero')));
/** Heroes hired as staff, per role: the first hire and the ace (see content.json and staff.ts). */
export const staffHeroes: Record<string, { hero: Hero; ace: Hero }> = Object.fromEntries(
  Object.entries(content.staff)
    .filter(([role]) => !role.startsWith('$'))
    .map(([role, v]) => {
      const ids = v as { hero: number; ace: number };
      return [role, { hero: toHero(byId(heroById, ids.hero, 'staff hero')), ace: toHero(byId(heroById, ids.ace, 'staff hero')) }];
    }),
);
/** Shady merchants who offer to buy up the stock (a decision event). */
export const merchants: Hero[] = content.merchantIds.map((id) => toHero(byId(heroById, id, 'merchant hero')));
const staffIds = new Set([...Object.values(staffHeroes).flatMap((s) => [s.hero.id, s.ace.id]), ...content.merchantIds]);

/** Customers: original heroes with a rarity, excluding the thieves and the staff. */
export const customers: Hero[] = raw.heroes
  .filter((h) => h.category === 'original' && h.rarity && RARITIES.includes(h.rarity as Rarity))
  .filter((h) => !content.thiefIds.includes(h.id) && !staffIds.has(h.id))
  .map(toHero);
export const customersByTier: Hero[][] = RARITIES.map((r) => customers.filter((c) => c.rarity === r));
const enemyById = new Map(raw.enemies.map((e) => [e.id, e]));
/** Enemies that get into the workshop (see content.json). */
export const pests = content.pestIds.map((id) => byId(enemyById, id, 'pest enemy'));
/** Enemies that wander into the shop and scare customers (see content.json). */
export const storePests = content.storePestIds.map((id) => byId(enemyById, id, 'store pest'));
/** Lands (guilds): window view on the land's day and its guardian cryptid. */
export const lands = raw.lands as { key: string; name: string; view: string; cryptid: string }[];
export const workshopImages = raw.workshop as Record<string, string>;
export const staffFrames = raw.staff as {
  chris: Frame[];
  chrisCheer: string;
  mine: Frame[];
  maycri: Frame[];
};
export const icons = raw.icons;

const allSeriesByKey = new Map(raw.series.map((s) => [s.key, s]));
/** Icon of any series in the asset database (not only the active ones), for decoration. */
export function seriesIcon(key: string, rarityIndex = 0): string {
  const s = allSeriesByKey.get(key);
  if (!s) throw new Error(`series ${key} not in catalog`);
  return s.items.filter((i) => !i.shin)[Math.min(rarityIndex, s.items.length - 1)].image;
}
export const audioFiles = raw.audio as Record<string, string>;
