// English names and descriptions of the hand-written skill nodes, by node id (applied in
// skills.ts when the game runs in English). Generated nodes — the series grid, staff, honor,
// blessings and hero sets — translate their own templates.

export const NODE_EN: Record<string, [name: string, desc: string]> = {
  root: ['Workshop Opens', 'Your crafting workshop. The arts of the five factions spread out from here'],

  // 朱雀 Suzaku: crafting
  craftSpeed: ['Pot Heat', 'Craft time -8%'],
  craftClick: ["Artisan's Touch", 'Pot tap effect +40%'],
  uncommon: ['Elite Method', 'Lets you craft Uncommon extensions'],
  double: ['Twin Craft', '5% chance to finish two at once'],
  forge: ['Fire Up the Forge', 'Line 2, the Forge, starts working. It specializes in arms and makes editions more often'],
  mine: ['Hire Mine-chan', 'Mine-chan stirs the pot at intervals (auto-tap; shorter interval per level)'],
  rare: ['Brave Method', 'Lets you craft Rare'],
  luck: ["Appraiser's Eye", 'Top-rarity chance +25% (all lines)'],
  craftSpeed2: ['Alchemy Secrets', 'Craft time -6%'],
  epic: ['Imperial Method', 'Lets you craft Epic'],
  legendary: ['MCH Method', 'Lets you craft Legendary'],
  potOverclock: ['Stirring Mastery', 'Pot speed while held +0.5×'],
  potCooling: ['Cooling Circle', 'Pot heats 10% slower and cools 15% faster'],
  forgeSpeed: ['Bellows', 'Forge craft time -8%'],
  forgeClick: ['Hammer Work', 'Forge tap effect +40%'],
  forgeDouble: ['Double Strike', 'Forge: 5% chance to finish two at once'],
  forgeTemper: ['Tempering', 'Forge edition chance +20%'],
  forgeOverclock: ['Great Bellows', 'Forge speed while held +0.5×'],
  forgeCooling: ['Water Trough', 'Forge heats 10% slower and cools 15% faster'],
  forgeSpeed2: ["Master Smith's Art", 'Forge craft time -6%'],
  appraisal: ['Appraisal', '"Appraised" editions (×1.6) start to appear'],
  engraving: ['Engraving', '"Engraved" editions (×3) start to appear'],
  autograph: ['Signing Event', 'Heroes\' "Signed" editions (×6) start to appear'],
  goldLeaf: ['Gold Leaf', '"Golden" editions (×15) start to appear'],
  editionLuck: ['Keen Eye', 'Edition chance +20% (all lines)'],
  shinForge: ['Shin Forging', 'Legendaries have a 3% chance to become Shin (×4)'],
  capsuleLine: ['Start the Capsule', 'Line 3, the Materialize Capsule, starts working. It makes beasts (price ×1.5). Comes with the Horse recipe'],
  capsuleSpeed: ['Culture Fluid', 'Capsule craft time -8%'],
  capsuleClick: ['Start Switch', 'Capsule tap effect +40%'],
  capsuleDouble: ['Twin Eggs', 'Capsule: 5% chance to finish two at once'],
  capsuleLuck: ['Summoning Circle', 'Capsule top-rarity chance +25%'],
  capsuleOverclock: ['Overcharge', 'Capsule speed while held +0.5×'],
  capsuleCooling: ['Coolant', 'Capsule heats 10% slower and cools 15% faster'],
  goldenExtension: ['Golden Extension', 'Proof of a legendary workshop: forge a golden extension with the arts of every series (clears the game). Sale price +100%'],

  // 青龍 Seiryu: customers
  ad: ['Barker', 'Customer rate +15%'],
  patience: ['Cozy Shop', 'Customers wait 1.5s longer'],
  tier1: ['Clientele: Uncommon', 'Uncommon heroes visit (pay ×1.25)'],
  walk: ['Signposts', 'Customer walking speed +12%'],
  lantern: ['Lantern Decor', 'Hang lanterns in the workshop. Customer rate +20%'],
  tier2: ['Clientele: Rare', 'Rare heroes visit (pay ×1.5)'],
  group: ['Group Customers', '8% chance a customer brings a friend'],
  wordOfMouth: ['Word of Mouth', 'Customer rate +6%'],
  tier3: ['Clientele: Epic', 'Epic heroes visit (pay ×1.8)'],
  tier4: ['Clientele: Legendary', 'Legendary heroes visit (pay ×2.2)'],
  festival: ['Street Stalls', 'Market-day crowds +10%'],
  carriage: ['Stagecoach', 'A stagecoach brings 4 customers at once every 40 seconds'],
  vehicleSize: ['Bigger Vehicles', 'Customers per vehicle +1'],
  airship: ['Airship', 'An airship brings 7 customers at once every 55 seconds (replaces the stagecoach)'],
  vehicleSpeed: ['Regular Service', 'Vehicle interval -10%'],
  landGate: ['Land Gate', 'A land gate brings 10 customers at once every 70 seconds'],
  collectors: ['Collectors', 'Collectors come looking for a particular series (they pay ×2 if they find it). Chance +6%'],
  collectorPay: ["Collector's Passion", 'Collectors pay +0.3×'],
  owner: ['Invite Land Owners', 'Land owners visit on other days too (they buy the best item at ×3). Chance +1%'],
  ownerPay: ['VIP Treatment', 'Land owners pay +0.4×'],
  legend: ['Legendary Visit', 'Chance of a legendary hero visiting +8% per day (sales ×2 while they stay)'],
  collectorStock: ['Well-Stocked Reputation', 'Collectors are more likely to look for a series on your shelves or in storage (+12%; 40% base, always at Lv 5)'],
  bespoke: ['Made to Order', "The workshop crafts what a waiting collector or ordering customer is after next, and hands it to them (even with full shelves)"],
  alternative: ['Something Else, Perhaps?', 'Collectors and ordering customers who run out of patience buy the priciest item on the shelves instead of leaving'],
  bigStore: ['Bigger Shop', 'Room for 4 more customers in the shop (24 base)'],
  bustling: ['Bustling Shop', 'Customer rate +10%'],
  safeShop: ['Peace of Mind', 'Chance of customers leaving over enemies in the shop or mud on the floor -65%'],
  orders: ['Take Orders', 'Heroes order their "favorite items" (1 order). Ordered items sell for ×3'],
  orderSlots: ['Order Book', 'Orders at a time +1'],
  orderPay: ['Custom Pricing', 'Ordered items sell for +0.5×'],
  orderFocus: ['Orders First', 'Series with an order are crafted even more often'],
  fanService: ['Fan Service', 'Familiar-face, regular and big-fan payment bonus +50%'],

  // 黄竜 Kouryu: prices and the register
  price: ['Smart Pricing', 'Sale price +15%'],
  cashier: ['Train Chris-kun', 'Checkout time -10%'],
  registerClick: ['Register Tapping', 'Register tap effect +40%'],
  dayLength: ['Longer Hours', 'Business day +8s'],
  tip: ['Hospitality', '10% chance of a tip (+50%)'],
  register: ['Extra Register', 'One more register (checks out in parallel)'],
  collector: ['Collection Know-how', 'Price bonus per collection entry +0.06%'],
  brand: ['Brand Power', 'Sale price +15%'],
  reputation: ['Spreading Fame', 'Sale price +5%. Lets you raise the reputation of each series'],
  autoRegister: ['Self Checkout', 'Adds a self-checkout (takes 1.6× as long as Chris-kun)'],
  batch: ['Batch Checkout', '8% chance to check out the next customer too'],
  market: ['Market Listing', 'While the shelves are full, sells spare stock by mail order one at a time (at 40% of the shop price)'],
  marketSpeed: ['Listing Routine', 'Listing interval -10%'],
  marketRate: ['Market Sense', 'Market price +3%'],

  // 白虎 Byakko: security and events
  bounty: ['Bounty', 'Reward for catching a thief +50%'],
  trap: ['Snare', 'Thief speed -12%'],
  bell: ['Alarm Bell', 'Thieves take 0.5s longer to steal'],
  guard: ['Maycri-kun on Guard', 'Maycri-kun catches fleeing thieves (chance +15%)'],
  ward: ['Pest Ward', 'Workshop enemy interval +20%'],
  exterminate: ['Pest Bounty', 'Reward for chasing off workshop enemies +100%'],
  umbrella: ['Umbrella Stand', 'Chance of mud on rainy days -20%'],
  fogLantern: ['Fog Lantern', 'Thieves on foggy days -15%, dropped coin value +20%'],
  cryptid: ["Cryptid's Guard", 'A cryptid guards the shop and strikes down enemies that get in with lightning'],
  cryptidSpeed: ['Lightning Rate', "Cryptid's lightning interval -15%"],
  storePestBounty: ['Chase-off Reward', 'Reward for chasing enemies out of the shop +50%'],
  chestHunter: ['Chest Sense', 'Treasure chests fly in 12% more often'],
  chestValue: ['Chest Contents', 'Treasure chest contents +25%'],
  negotiation: ['Haggling', "Merchant's offer +4% (of what customers would pay)"],
  reform: ['Persuasion', 'Chance a caught thief asks to reform +10%'],
  regularPay: ['Bond with Regulars', 'Regulars (reformed thieves) pay +10%'],
  blessing: ["MAI's Cheer", "MAI's help (sales boost) lasts 25% longer"],

  // 玄武 Genbu: shelves, storage, dismantling
  shelf: ['More Shelves', 'Display slots +1'],
  displayTable: ['Display Tables', 'Puts display tables in front of the shop lane (display slots +4). Available once More Shelves is maxed'],
  tableMore: ['More Tables', 'Display table slots +1 (up to 4 tables)'],
  collectorFetch: ['Fetch from Storage', "When a collector's series is in storage, it goes on the shelf first (swapped for an item nobody is after if the shelves are full)"],
  collectorFocus: ['Collectors First', 'Series that collectors in the shop are looking for are crafted more often'],
  conveyor: ['Conveyor Lane', 'Adds a conveyor lane. Up to 4 items wait in storage when the shelves are full'],
  storage: ['Bigger Storage', 'Storage capacity +3'],
  packer: ['Packer', 'Restocks the shelves from storage quickly, pricier items first'],
  dismantle: ['Dismantler', 'When there is no room, breaks plain Common items down into gold dust and magic stones'],
  dismantleRarity: ['Hotter Furnace', 'Dismantler handles one more rarity (Uncommon → Rare)'],
  dustYield: ['Refining', 'Gold dust from dismantling +25%'],
  gemChance: ['Stone Sense', 'Magic stone chance when dismantling +10%'],
  infusion: ['Stone Infusion', 'Before opening, infuse a magic stone into each line to boost it for the day (2 per day)'],
  infusionPower: ['Stone Resonance', 'Magic stone effect +25%'],
  recipeBook: ['Recipe Book', 'Start collecting series recipes. A varied range: customer rate +5%'],
  planning: ['Production Planning', 'Unlocks Mass Production for each series. Craft time -3% (all lines)'],
  masterwork: ['Masterpiece Appraisal', 'Unlocks Masterpiece for each series. Edition chance +5%'],
  beastBook: ['Book of Beasts', 'Opens the beast rows (Horse reputation, production and masterpiece, and beast recipes). A wider range: customer rate +3%'],

  // 店舗 Store: facilities
  decor: ['Interior Work', 'Lets you place fixtures on the shop floor. Customer rate +5%'],
  rug: ['Luxury Rug', 'Customers choose 8% faster and wait 0.4s longer at the shelf'],
  potionStand: ['Potion Stand', 'Hands out free potions at the door. Customer walking speed +8%'],
  potionTaste: ['Potion Flavor', 'Customers wait 0.5s longer at shelves and registers'],
  potionBar: ['Potion Bar', '6% of customers stop for a drink after shopping (20% of their purchase)'],
  barMenu: ['New Menu', 'Price of a potion +3% (of the purchase)'],
  trial: ['Test-Cutting Range', '5% of customers try out what they bought (25% of their purchase)'],
  trialFee: ['Range Fee', 'Test-cutting fee +3% (of the purchase)'],
  showcase: ['Showcase', 'A special shelf for Rare+ and edition items +1 slot (price ×1.5)'],
  showcaseLight: ['Showcase Lights', 'Showcase price +0.1×'],

  // 研究 Research
  lab: ['Laboratory', 'Opens the research branch. Research points +0.5/min'],
  rsEconomy: ['Business Studies', 'Sale price +4%'],
  rsAlchemy: ['Alchemy Research', 'Craft time -5% (all lines)'],
  rsPsychology: ['Psychology', 'Customers wait 1s longer at shelves and registers; pricier items picked 3% more often'],
  rsStatistics: ['Statistics', 'Top-rarity chance +15% (all lines)'],
  rsMetallurgy: ['Metallurgy', 'Edition chance +8%'],
  rsLogistics: ['Logistics', 'Storage capacity +2, restock interval -8%'],
  rsAstronomy: ['Astronomy', 'Business day +4s'],
  rsEconomics: ['Economics', 'Closing sales bonus +1%, market price +2%'],
  rsSecurity: ['Security Studies', 'Thief speed -8%, guard speed +8%'],
  rsBiology: ['Biology', 'Capsule top-rarity chance +20%'],
  rsArchaeology: ['Archaeology', 'Price bonus per collection entry +0.02%'],
  rsAutomation: ['Automation Theory', 'Self-checkouts +1'],
  rsGrandTheory: ['Grand Unified Theory', 'Sale price +25%'],

  // 名誉 Honor
  honorHub: ['Hall of Honor', 'Spend emblems from achievements and daily requests on permanent perks'],

  // 移転 Relocation (paid in Cp)
  relocation: ['Relocation Know-how', 'Gateway to the relocation perks, bought with Cp (earned by relocating after the clear). Sale price +10%'],
  startGum: ['Moving Funds', 'Start the next run with 1,000 → 100K → 10M → 1B GUM'],
  oldShop: ['Long-Established', 'Sale price +25%'],
  craftsman: ['Veteran Artisans', 'Craft time -10% (all lines)'],
  keepRecipes: ['Inherited Recipe Book', 'Take the first 5 recipes along when you relocate'],
  longQueue: ['Queue Out the Door', 'Customer rate +15%'],
  dawn: ['Dawn Opening', 'Business day +6s'],
  cpBoost: ['Vessel of Fame', 'Cp from relocating +20%'],
  memory: ['Collection Memory', 'Price bonus per collection entry +0.05%'],
  scholar: ['Accumulated Research', 'Research points +50%'],
  charityUnlock: ['Spirit of Giving', 'Lets you hire a Charity Clerk (donate unsold stock for fame → Cp)'],
  autoBuyer: ['Head Clerk', 'After closing, buys GUM skills cheapest first (toggle in the menu)'],
  raidReward: ['Pirate-Hunting Reward', 'Reward for repelling a raid +50%'],
};
